In [1]:
import pandas as pd 
import numpy as np 
from sklearn.feature_selection import SelectKBest, RFE, f_regression, SequentialFeatureSelector
import seaborn as sns
from pydataset import data

In [2]:
tips = sns.load_dataset("tips")

In [3]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [5]:
#Create a column called price per person that divides total bill by party size 
tips['price_per_person']= (tips['total_bill']/tips['size']).round(2)

In [6]:
tips

     total_bill   tip     sex smoker   day    time  size  price_per_person
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15
..          ...   ...     ...    ...   ...     ...   ...               ...
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39

[244 rows x 8 columns]

Which features do I think predict the tip amount?

- size

In [7]:
#creating sample of train data from overall dataset 
train = tips.sample(frac=.5)

In [8]:
train

     total_bill    tip     sex smoker   day    time  size  price_per_person
85        34.83   5.17  Female     No  Thur   Lunch     4              8.71
113       23.95   2.55    Male     No   Sun  Dinner     2             11.98
11        35.26   5.00  Female     No   Sun  Dinner     4              8.82
170       50.81  10.00    Male    Yes   Sat  Dinner     3             16.94
37        16.93   3.07  Female     No   Sat  Dinner     3              5.64
219       30.14   3.09  Female    Yes   Sat  Dinner     4              7.54
128       11.38   2.00  Female     No  Thur   Lunch     2              5.69
179       34.63   3.55    Male    Yes   Sun  Dinner     2             17.32
98        21.01   3.00    Male    Yes   Fri  Dinner     2             10.50
122       14.26   2.50    Male     No  Thur   Lunch     2              7.13
177       14.48   2.00    Male    Yes   Sun  Dinner     2              7.24
147       11.87   1.63  Female     No  Thur   Lunch     2              5.94
140       17.47   3.50  Female     No  Thur   Lunch     2              8.74
119       24.08   2.92  Female     No  Thur   Lunch     4              6.02
120       11.69   2.31    Male     No  Thur   Lunch     2              5.84
42        13.94   3.06    Male     No   Sun  Dinner     2              6.97
224       13.42   1.58    Male    Yes   Fri   Lunch     2              6.71
8         15.04   1.96    Male     No   Sun  Dinner     2              7.52
168       10.59   1.61  Female    Yes   Sat  Dinner     2              5.30
180       34.65   3.68    Male    Yes   Sun  Dinner     4              8.66
236       12.60   1.00    Male    Yes   Sat  Dinner     2              6.30
172        7.25   5.15    Male    Yes   Sun  Dinner     2              3.62
56        38.01   3.00    Male    Yes   Sat  Dinner     4              9.50
23        39.42   7.58    Male     No   Sat  Dinner     4              9.86
199       13.51   2.00    Male    Yes  Thur   Lunch     2              6.76
187       30.46   2.00    Male    Yes   Sun  Dinner     5              6.09
145        8.35   1.50  Female     No  Thur   Lunch     2              4.18
35        24.06   3.60    Male     No   Sat  Dinner     3              8.02
27        12.69   2.00    Male     No   Sat  Dinner     2              6.34
220       12.16   2.20    Male    Yes   Fri   Lunch     2              6.08
82        10.07   1.83  Female     No  Thur   Lunch     1             10.07
226       10.09   2.00  Female    Yes   Fri   Lunch     2              5.04
150       14.07   2.50    Male     No   Sun  Dinner     2              7.04
167       31.71   4.50    Male     No   Sun  Dinner     4              7.93
181       23.33   5.65    Male    Yes   Sun  Dinner     2             11.66
197       43.11   5.00  Female    Yes  Thur   Lunch     4             10.78
200       18.71   4.00    Male    Yes  Thur   Lunch     3              6.24
68        20.23   2.01    Male     No   Sat  Dinner     2             10.12
189       23.10   4.00    Male    Yes   Sun  Dinner     3              7.70
233       10.77   1.47    Male     No   Sat  Dinner     2              5.38
26        13.37   2.00    Male     No   Sat  Dinner     2              6.68
206       26.59   3.41    Male    Yes   Sat  Dinner     3              8.86
86        13.03   2.00    Male     No  Thur   Lunch     2              6.52
218        7.74   1.44    Male    Yes   Sat  Dinner     2              3.87
73        25.28   5.00  Female    Yes   Sat  Dinner     2             12.64
4         24.59   3.61  Female     No   Sun  Dinner     4              6.15
61        13.81   2.00    Male    Yes   Sat  Dinner     2              6.90
38        18.69   2.31    Male     No   Sat  Dinner     3              6.23
109       14.31   4.00  Female    Yes   Sat  Dinner     2              7.16
210       30.06   2.00    Male    Yes   Sat  Dinner     3             10.02
76        17.92   3.08    Male    Yes   Sat  Dinner     2              8.96
112       38.07   4.00    Male     No   Sun  Dinner     3             12.69
176       17.89   2.00    Male    Yes   Sun  Dinner     2              8.94
186       20.90   3.50  Female    Yes   Sun  Dinner     3              6.97
87        18.28   4.00    Male     No  Thur   Lunch     2              9.14
143       27.05   5.00  Female     No  Thur   Lunch     6              4.51
17        16.29   3.71    Male     No   Sun  Dinner     3              5.43
51        10.29   2.60  Female     No   Sun  Dinner     2              5.14
148        9.78   1.73    Male     No  Thur   Lunch     2              4.89
111        7.25   1.00  Female     No   Sat  Dinner     1              7.25
159       16.49   2.00    Male     No   Sun  Dinner     4              4.12
12        15.42   1.57    Male     No   Sun  Dinner     2              7.71
104       20.92   4.08  Female     No   Sat  Dinner     2             10.46
18        16.97   3.50  Female     No   Sun  Dinner     3              5.66
78        22.76   3.00    Male     No  Thur   Lunch     2             11.38
45        18.29   3.00    Male     No   Sun  Dinner     2              9.14
173       31.85   3.18    Male    Yes   Sun  Dinner     2             15.92
47        32.40   6.00    Male     No   Sun  Dinner     4              8.10
84        15.98   2.03    Male     No  Thur   Lunch     2              7.99
239       29.03   5.92    Male     No   Sat  Dinner     3              9.68
71        17.07   3.00  Female     No   Sat  Dinner     3              5.69
95        40.17   4.73    Male    Yes   Fri  Dinner     4             10.04
193       15.48   2.02    Male    Yes  Thur   Lunch     2              7.74
81        16.66   3.40    Male     No  Thur   Lunch     2              8.33
131       20.27   2.83  Female     No  Thur   Lunch     2             10.14
229       22.12   2.88  Female    Yes   Sat  Dinner     2             11.06
162       16.21   2.00  Female     No   Sun  Dinner     3              5.40
40        16.04   2.24    Male     No   Sat  Dinner     3              5.35
105       15.36   1.64    Male    Yes   Sat  Dinner     2              7.68
62        11.02   1.98    Male    Yes   Sat  Dinner     2              5.51
214       28.17   6.50  Female    Yes   Sat  Dinner     3              9.39
138       16.00   2.00    Male    Yes  Thur   Lunch     2              8.00
217       11.59   1.50    Male    Yes   Sat  Dinner     2              5.80
93        16.32   4.30  Female    Yes   Fri  Dinner     2              8.16
157       25.00   3.75  Female     No   Sun  Dinner     4              6.25
202       13.00   2.00  Female    Yes  Thur   Lunch     2              6.50
154       19.77   2.00    Male     No   Sun  Dinner     4              4.94
63        18.29   3.76    Male    Yes   Sat  Dinner     4              4.57
31        18.35   2.50    Male     No   Sat  Dinner     4              4.59
0         16.99   1.01  Female     No   Sun  Dinner     2              8.49
13        18.43   3.00    Male     No   Sun  Dinner     4              4.61
163       13.81   2.00    Male     No   Sun  Dinner     2              6.90
182       45.35   3.50    Male    Yes   Sun  Dinner     3             15.12
94        22.75   3.25  Female     No   Fri  Dinner     2             11.38
205       16.47   3.23  Female    Yes  Thur   Lunch     3              5.49
169       10.63   2.00  Female    Yes   Sat  Dinner     2              5.32
91        22.49   3.50    Male     No   Fri  Dinner     2             11.24
171       15.81   3.16    Male    Yes   Sat  Dinner     2              7.90
100       11.35   2.50  Female    Yes   Fri  Dinner     2              5.68
188       18.15   3.50  Female    Yes   Sun  Dinner     3              6.05
228       13.28   2.72    Male     No   Sat  Dinner     2              6.64
183       23.17   6.50    Male    Yes   Sun  Dinner     4              5.79
116       29.93   5.07    Male     No   Sun  Dinner     4              7.48
24        19.82   3.18    Male     No   Sat  Dinner     2              9.91
2         21.01   3.50    Male     No   Sun  Dinner     3              7.00
90        28.97   3.00    Male    Yes   Fri  Dinner     2             14.48
129       22.82   2.18    Male     No  Thur   Lunch     3              7.61
33        20.69   2.45  Female     No   Sat  Dinner     4              5.17
110       14.00   3.00    Male     No   Sat  Dinner     2              7.00
161       12.66   2.50    Male     No   Sun  Dinner     2              6.33
107       25.21   4.29    Male    Yes   Sat  Dinner     2             12.60
192       28.44   2.56    Male    Yes  Thur   Lunch     2             14.22
53         9.94   1.56    Male     No   Sun  Dinner     2              4.97
213       13.27   2.50  Female    Yes   Sat  Dinner     2              6.64
54        25.56   4.34    Male     No   Sun  Dinner     4              6.39
232       11.61   3.39    Male     No   Sat  Dinner     2              5.80
133       12.26   2.00  Female     No  Thur   Lunch     2              6.13
106       20.49   4.06    Male    Yes   Sat  Dinner     2             10.24
41        17.46   2.54    Male     No   Sun  Dinner     2              8.73
67         3.07   1.00  Female    Yes   Sat  Dinner     1              3.07
15        21.58   3.92    Male     No   Sun  Dinner     2             10.79
130       19.08   1.50    Male     No  Thur   Lunch     2              9.54

In [9]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 122 entries, 85 to 130
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        122 non-null    float64
 1   tip               122 non-null    float64
 2   sex               122 non-null    category
 3   smoker            122 non-null    category
 4   day               122 non-null    category
 5   time              122 non-null    category
 6   size              122 non-null    int64
 7   price_per_person  122 non-null    float64
dtypes: category(4), float64(3), int64(1)
memory usage: 5.8 KB

In [10]:
train['size']=train['size'].astype(float)

In [11]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 122 entries, 85 to 130
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        122 non-null    float64
 1   tip               122 non-null    float64
 2   sex               122 non-null    category
 3   smoker            122 non-null    category
 4   day               122 non-null    category
 5   time              122 non-null    category
 6   size              122 non-null    float64
 7   price_per_person  122 non-null    float64
dtypes: category(4), float64(4)
memory usage: 5.8 KB

In [12]:
dummy_df = pd.get_dummies(train[['smoker',\
                              'sex', \
                              'day', \
                              'time']], dummy_na=False, \
                              drop_first=True)

In [13]:
train = pd.concat([train, dummy_df], axis=1)

In [15]:
train

,total_bill,tip,sex,smoker,day,time,size,price_per_person,smoker_No,sex_Female,day_Fri,day_Sat,day_Sun,time_Dinner
85,34.83,5.17,Female,No,Thur,Lunch,4.0,8.71,1,1,0,0,0,0
113,23.95,2.55,Male,No,Sun,Dinner,2.0,11.98,1,0,0,0,1,1
11,35.26,5.00,Female,No,Sun,Dinner,4.0,8.82,1,1,0,0,1,1
170,50.81,10.00,Male,Yes,Sat,Dinner,3.0,16.94,0,0,0,1,0,1
37,16.93,3.07,Female,No,Sat,Dinner,3.0,5.64,1,1,0,1,0,1
219,30.14,3.09,Female,Yes,Sat,Dinner,4.0,7.54,0,1,0,1,0,1
128,11.38,2.00,Female,No,Thur,Lunch,2.0,5.69,1,1,0,0,0,0
179,34.63,3.55,Male,Yes,Sun,Dinner,2.0,17.32,0,0,0,0,1,1
98,21.01,3.00,Male,Yes,Fri,Dinner,2.0,10.50,0,0,1,0,0,1
122,14.26,2.50,Male,No,Thur,Lunch,2.0,7.13,1,0,0,0,0,0
177,14.48,2.00,Male,Yes,Sun,Dinner,2.0,7.24,0,0,0,0,1,1
147,11.87,1.63,Female,No,Thur,Lunch,2.0,5.94,1,1,0,0,0,0
140,17.47,3.50,Female,No,Thur,Lunch,2.0,8.74,1,1,0,0,0,0
119,24.08,2.92,Female,No,Thur,Lunch,4.0,6.02,1,1,0,0,0,0
120,11.69,2.31,Male,No,Thur,Lunch,2.0,5.84,1,0,0,0,0,0
42,13.94,3.06,Male,No,Sun,Dinner,2.0,6.97,1,0,0,0,1,1
224,13.42,1.58,Male,Yes,Fri,Lunch,2.0,6.71,0,0,1,0,0,0
8,15.04,1.96,Male,No,Sun,Dinner,2.0,7.52,1,0,0,0,1,1
168,10.59,1.61,Female,Yes,Sat,Dinner,2.0,5.30,0,1,0,1,0,1
180,34.65,3.68,Male,Yes,Sun,Dinner,4.0,8.66,0,0,0,0,1,1
236,12.60,1.00,Male,Yes,Sat,Dinner,2.0,6.30,0,0,0,1,0,1
172,7.25,5.15,Male,Yes,Sun,Dinner,2.0,3.62,0,0,0,0,1,1
56,38.01,3.00,Male,Yes,Sat,Dinner,4.0,9.50,0,0,0,1,0,1
23,39.42,7.58,Male,No,Sat,Dinner,4.0,9.86,1,0,0,1,0,1
199,13.51,2.00,Male,Yes,Thur,Lunch,2.0,6.76,0,0,0,0,0,0
187,30.46,2.00,Male,Yes,Sun,Dinner,5.0,6.09,0,0,0,0,1,1
145,8.35,1.50,Female,No,Thur,Lunch,2.0,4.18,1,1,0,0,0,0
35,24.06,3.60,Male,No,Sat,Dinner,3.0,8.02,1,0,0,1,0,1
27,12.69,2.00,Male,No,Sat,Dinner,2.0,6.34,1,0,0,1,0,1
220,12.16,2.20,Male,Yes,Fri,Lunch,2.0,6.08,0,0,1,0,0,0
82,10.07,1.83,Female,No,Thur,Lunch,1.0,10.07,1,1,0,0,0,0
226,10.09,2.00,Female,Yes,Fri,Lunch,2.0,5.04,0,1,1,0,0,0
150,14.07,2.50,Male,No,Sun,Dinner,2.0,7.04,1,0,0,0,1,1
167,31.71,4.50,Male,No,Sun,Dinner,4.0,7.93,1,0,0,0,1,1
181,23.33,5.65,Male,Yes,Sun,Dinner,2.0,11.66,0,0,0,0,1,1
197,43.11,5.00,Female,Yes,Thur,Lunch,4.0,10.78,0,1,0,0,0,0
200,18.71,4.00,Male,Yes,Thur,Lunch,3.0,6.24,0,0,0,0,0,0
68,20.23,2.01,Male,No,Sat,Dinner,2.0,10.12,1,0,0,1,0,1
189,23.10,4.00,Male,Yes,Sun,Dinner,3.0,7.70,0,0,0,0,1,1
233,10.77,1.47,Male,No,Sat,Dinner,2.0,5.38,1,0,0,1,0,1
26,13.37,2.00,Male,No,Sat,Dinner,2.0,6.68,1,0,0,1,0,1
206,26.59,3.41,Male,Yes,Sat,Dinner,3.0,8.86,0,0,0,1,0,1
86,13.03,2.00,Male,No,Thur,Lunch,2.0,6.52,1,0,0,0,0,0
218,7.74,1.44,Male,Yes,Sat,Dinner,2.0,3.87,0,0,0,1,0,1
73,25.28,5.00,Female,Yes,Sat,Dinner,2.0,12.64,0,1,0,1,0,1
4,24.59,3.61,Female,No,Sun,Dinner,4.0,6.15,1,1,0,0,1,1
61,13.81,2.00,Male,Yes,Sat,Dinner,2.0,6.90,0,0,0,1,0,1
38,18.69,2.31,Male,No,Sat,Dinner,3.0,6.23,1,0,0,1,0,1
109,14.31,4.00,Female,Yes,Sat,Dinner,2.0,7.16,0,1,0,1,0,1
210,30.06,2.00,Male,Yes,Sat,Dinner,3.0,10.02,0,0,0,1,0,1
76,17.92,3.08,Male,Yes,Sat,Dinner,2.0,8.96,0,0,0,1,0,1
112,38.07,4.00,Male,No,Sun,Dinner,3.0,12.69,1,0,0,0,1,1
176,17.89,2.00,Male,Yes,Sun,Dinner,2.0,8.94,0,0,0,0,1,1
186,20.90,3.50,Female,Yes,Sun,Dinner,3.0,6.97,0,1,0,0,1,1
87,18.28,4.00,Male,No,Thur,Lunch,2.0,9.14,1,0,0,0,0,0
143,27.05,5.00,Female,No,Thur,Lunch,6.0,4.51,1,1,0,0,0,0
17,16.29,3.71,Male,No,Sun,Dinner,3.0,5.43,1,0,0,0,1,1
51,10.29,2.60,Female,No,Sun,Dinner,2.0,5.14,1,1,0,0,1,1
148,9.78,1.73,Male,No,Thur,Lunch,2.0,4.89,1,0,0,0,0,0
111,7.25,1.00,Female,No,Sat,Dinner,1.0,7.25,1,1,0,1,0,1
159,16.49,2.00,Male,No,Sun,Dinner,4.0,4.12,1,0,0,0,1,1
12,15.42,1.57,Male,No,Sun,Dinner,2.0,7.71,1,0,0,0,1,1
104,20.92,4.08,Female,No,Sat,Dinner,2.0,10.46,1,1,0,1,0,1
18,16.97,3.50,Female,No,Sun,Dinner,3.0,5.66,1,1,0,0,1,1
78,22.76,3.00,Male,No,Thur,Lunch,2.0,11.38,1,0,0,0,0,0
45,18.29,3.00,Male,No,Sun,Dinner,2.0,9.14,1,0,0,0,1,1
173,31.85,3.18,Male,Yes,Sun,Dinner,2.0,15.92,0,0,0,0,1,1
47,32.40,6.00,Male,No,Sun,Dinner,4.0,8.10,1,0,0,0,1,1
84,15.98,2.03,Male,No,Thur,Lunch,2.0,7.99,1,0,0,0,0,0
239,29.03,5.92,Male,No,Sat,Dinner,3.0,9.68,1,0,0,1,0,1
71,17.07,3.00,Female,No,Sat,Dinner,3.0,5.69,1,1,0,1,0,1
95,40.17,4.73,Male,Yes,Fri,Dinner,4.0,10.04,0,0,1,0,0,1
193,15.48,2.02,Male,Yes,Thur,Lunch,2.0,7.74,0,0,0,0,0,0
81,16.66,3.40,Male,No,Thur,Lunch,2.0,8.33,1,0,0,0,0,0
131,20.27,2.83,Female,No,Thur,Lunch,2.0,10.14,1,1,0,0,0,0
229,22.12,2.88,Female,Yes,Sat,Dinner,2.0,11.06,0,1,0,1,0,1
162,16.21,2.00,Female,No,Sun,Dinner,3.0,5.40,1,1,0,0,1,1
40,16.04,2.24,Male,No,Sat,Dinner,3.0,5.35,1,0,0,1,0,1
105,15.36,1.64,Male,Yes,Sat,Dinner,2.0,7.68,0,0,0,1,0,1
62,11.02,1.98,Male,Yes,Sat,Dinner,2.0,5.51,0,0,0,1,0,1
214,28.17,6.50,Female,Yes,Sat,Dinner,3.0,9.39,0,1,0,1,0,1
138,16.00,2.00,Male,Yes,Thur,Lunch,2.0,8.00,0,0,0,0,0,0
217,11.59,1.50,Male,Yes,Sat,Dinner,2.0,5.80,0,0,0,1,0,1
93,16.32,4.30,Female,Yes,Fri,Dinner,2.0,8.16,0,1,1,0,0,1
157,25.00,3.75,Female,No,Sun,Dinner,4.0,6.25,1,1,0,0,1,1
202,13.00,2.00,Female,Yes,Thur,Lunch,2.0,6.50,0,1,0,0,0,0
154,19.77,2.00,Male,No,Sun,Dinner,4.0,4.94,1,0,0,0,1,1
63,18.29,3.76,Male,Yes,Sat,Dinner,4.0,4.57,0,0,0,1,0,1
31,18.35,2.50,Male,No,Sat,Dinner,4.0,4.59,1,0,0,1,0,1
0,16.99,1.01,Female,No,Sun,Dinner,2.0,8.49,1,1,0,0,1,1
13,18.43,3.00,Male,No,Sun,Dinner,4.0,4.61,1,0,0,0,1,1
163,13.81,2.00,Male,No,Sun,Dinner,2.0,6.90,1,0,0,0,1,1
182,45.35,3.50,Male,Yes,Sun,Dinner,3.0,15.12,0,0,0,0,1,1
94,22.75,3.25,Female,No,Fri,Dinner,2.0,11.38,1,1,1,0,0,1
205,16.47,3.23,Female,Yes,Thur,Lunch,3.0,5.49,0,1,0,0,0,0
169,10.63,2.00,Female,Yes,Sat,Dinner,2.0,5.32,0,1,0,1,0,1
91,22.49,3.50,Male,No,Fri,Dinner,2.0,11.24,1,0,1,0,0,1
171,15.81,3.16,Male,Yes,Sat,Dinner,2.0,7.90,0,0,0,1,0,1
100,11.35,2.50,Female,Yes,Fri,Dinner,2.0,5.68,0,1,1,0,0,1
188,18.15,3.50,Female,Yes,Sun,Dinner,3.0,6.05,0,1,0,0,1,1
228,13.28,2.72,Male,No,Sat,Dinner,2.0,6.64,1,0,0,1,0,1
183,23.17,6.50,Male,Yes,Sun,Dinner,4.0,5.79,0,0,0,0,1,1
116,29.93,5.07,Male,No,Sun,Dinner,4.0,7.48,1,0,0,0,1,1
24,19.82,3.18,Male,No,Sat,Dinner,2.0,9.91,1,0,0,1,0,1
2,21.01,3.50,Male,No,Sun,Dinner,3.0,7.00,1,0,0,0,1,1
90,28.97,3.00,Male,Yes,Fri,Dinner,2.0,14.48,0,0,1,0,0,1
129,22.82,2.18,Male,No,Thur,Lunch,3.0,7.61,1,0,0,0,0,0
33,20.69,2.45,Female,No,Sat,Dinner,4.0,5.17,1,1,0,1,0,1
110,14.00,3.00,Male,No,Sat,Dinner,2.0,7.00,1,0,0,1,0,1
161,12.66,2.50,Male,No,Sun,Dinner,2.0,6.33,1,0,0,0,1,1
107,25.21,4.29,Male,Yes,Sat,Dinner,2.0,12.60,0,0,0,1,0,1
192,28.44,2.56,Male,Yes,Thur,Lunch,2.0,14.22,0,0,0,0,0,0
53,9.94,1.56,Male,No,Sun,Dinner,2.0,4.97,1,0,0,0,1,1
213,13.27,2.50,Female,Yes,Sat,Dinner,2.0,6.64,0,1,0,1,0,1
54,25.56,4.34,Male,No,Sun,Dinner,4.0,6.39,1,0,0,0,1,1
232,11.61,3.39,Male,No,Sat,Dinner,2.0,5.80,1,0,0,1,0,1
133,12.26,2.00,Female,No,Thur,Lunch,2.0,6.13,1,1,0,0,0,0
106,20.49,4.06,Male,Yes,Sat,Dinner,2.0,10.24,0,0,0,1,0,1
41,17.46,2.54,Male,No,Sun,Dinner,2.0,8.73,1,0,0,0,1,1
67,3.07,1.00,Female,Yes,Sat,Dinner,1.0,3.07,0,1,0,1,0,1
15,21.58,3.92,Male,No,Sun,Dinner,2.0,10.79,1,0,0,0,1,1
130,19.08,1.50,Male,No,Thur,Lunch,2.0,9.54,1,0,0,0,0,0

In [ ]:
tips.pairplot

In [ ]:
tips.corr()

In [16]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 122 entries, 85 to 130
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        122 non-null    float64
 1   tip               122 non-null    float64
 2   sex               122 non-null    category
 3   smoker            122 non-null    category
 4   day               122 non-null    category
 5   time              122 non-null    category
 6   size              122 non-null    float64
 7   price_per_person  122 non-null    float64
 8   smoker_No         122 non-null    uint8
 9   sex_Female        122 non-null    uint8
 10  day_Fri           122 non-null    uint8
 11  day_Sat           122 non-null    uint8
 12  day_Sun           122 non-null    uint8
 13  time_Dinner       122 non-null    uint8
dtypes: category(4), float64(4), uint8(6)
memory usage: 6.5 KB

In [19]:
#selecting columns to be placed in model
cols =['total_bill','size','price_per_person','sex_Female','day_Fri','day_Sat','day_Sun','smoker_No','time_Dinner']

In [20]:
#designating x and y train
X_train, y_train = train[cols], train['tip']

## use k best to select the top 2 features for predicting tip amount what are they?

In [21]:
# make the thing
kbest = SelectKBest(f_regression, k=2)
# fit the thing
_ = kbest.fit(X_train, y_train)

In [22]:
# statistical f-value:
#high number for score is good 
kbest.scores_ 
#p value: 
kbest.pvalues_

array([8.63723697e-18, 1.64897823e-07, 5.35351845e-06, 8.84465504e-01,
       9.01365395e-01, 9.09836554e-01, 2.00516602e-01, 3.65645327e-01,
       5.23740958e-02])

In [23]:
kbest_results = pd.DataFrame(
    dict(p=kbest.pvalues_, f=kbest.scores_),
                             index = X_train.columns)

#f score ratio between explained variance and unexplained variance , higher f score the better. 
#How much error is explained in test

In [24]:
kbest_results

                             p           f
total_bill        8.637237e-18  102.503155
size              1.648978e-07   30.929430
price_per_person  5.353518e-06   22.701573
sex_Female        8.844655e-01    0.021205
day_Fri           9.013654e-01    0.015425
day_Sat           9.098366e-01    0.012879
day_Sun           2.005166e-01    1.656774
smoker_No         3.656453e-01    0.824646
time_Dinner       5.237410e-02    3.839600

In [25]:
# get-support() will output a boolean mask to tell me which features were selected
# we can apply this mask to the columns in our original dataframe
# not helpful if you only have 10 columns (good for hundreds of columns in data set)
# Function is picking best columns (2 in this example because K was 2)
X_train.columns[kbest.get_support()]

Index(['total_bill', 'size'], dtype='object')

In [26]:
# kbest transform will convert our information to the selected feature subspace
# this provides numpy array
kbest.transform(X_train)[:5]

array([[34.83,  4.  ],
       [23.95,  2.  ],
       [35.26,  4.  ],
       [50.81,  3.  ],
       [16.93,  3.  ]])

In [27]:
# convert kbest transform back to dataframe
X_train_transformed = pd.DataFrame(
    kbest.transform(X_train),
    columns=X_train.columns[kbest.get_support()],
    index=X_train.index
)

In [28]:
X_train_transformed.head()

     total_bill  size
85        34.83   4.0
113       23.95   2.0
11        35.26   4.0
170       50.81   3.0
37        16.93   3.0

k best is saying to keep total bill and size

## use recursive feature elimination to select the top 2 features. What are they?

In [31]:
from sklearn.linear_model import LinearRegression

In [32]:
# make a model object to use in RFE process.
# The model is here to give us metrics on feature importance and model score
# allowing us to recursively reduce the number of features to reach our desired space
model = LinearRegression()

In [33]:
# make thing
rfe = RFE(model, n_features_to_select=2)
# fit thing
rfe.fit(X_train, y_train)

RFE(estimator=LinearRegression(), n_features_to_select=2)

In [34]:
#create rankings 
# keeping 1 and removing 2
rfe.ranking_

array([2, 3, 7, 1, 5, 6, 4, 8, 1])

In [35]:
# converting ranking back into dataframe
pd.DataFrame(
{
    'rfe_ranking': rfe.ranking_
},index = X_train.columns)

                  rfe_ranking
total_bill                  2
size                        3
price_per_person            7
sex_Female                  1
day_Fri                     5
day_Sat                     6
day_Sun                     4
smoker_No                   8
time_Dinner                 1

recursive model is stating to keep price_per_person and total_bill

## Why do you think select k best and recursive feature elimination might give different answers for the top features? Does this change as you change the number of features you are selecting?

There is probably a differnece because of how they evaluate the features. 
K best evaluates the features based on the strength of the relationship to the target variable. 
Recursive evaluates the features based on their resulting coefficent 
starting from differnt points, order matters.
the way they handle independent variables. Select K best in vacuum. rfe takes into account relationship of variables all together

##  Write a function named select_kbest that takes in the predictors (X), the target (y), and the number of features to select (k) and returns the names of the top k selected features based on the SelectKBest class. Test your function with the tips dataset. You should see the same results as when you did the process manually.

In [37]:
def select_kbest(X,y,z):
    '''This function will provide the results of the best features for 
    predicting the target using Select K best '''
    
    # make the thing
    kbest = SelectKBest(f_regression, k=z)
    # fit the thing
    _ = kbest.fit(X, y)
    
    # statistical f-value:
    kbest.scores_ 
    #p value: 
    kbest.pvalues_
    X.columns[kbest.get_support()]
    
    #placing kbest results into dataframe
    kbest_results = pd.DataFrame(
    dict(p=kbest.pvalues_, f=kbest.scores_),
                             index = X.columns)
    
    #lists best features based on value of k
    return X.columns[kbest.get_support()]

## Write a function named rfe that takes in the predictors, the target, and the number of features to select. It should return the top k features based on the RFE class. Test your function with the tips dataset. You should see the same results as when you did the process manually.

In [38]:
def select_rfe(X,y,k):
    '''this function will provide the top k features baed on the RFE class'''

    #creating linearRegression model for rfe 
    model = LinearRegression()
    
    # make rfe
    rfe = RFE(model, n_features_to_select=k)
    
    # fit rfe on data
    rfe.fit(X, y)
    
    #apply ranking to features
    rfe.ranking_
    
    #turn ranking results into dataframe
    pd.DataFrame(
    {
        'rfe_ranking': rfe.ranking_
    },index = X.columns)
    
    #boolean mask for ranking of features 
    rfe.get_support()
    
    #transform get support into dataframe of top k features
    X_transformed = pd.DataFrame(
    rfe.transform(X),
    index = X.index,
    columns = X.columns[rfe.support_])
    
    #shows k top columns
    return X_transformed

## Load the swiss dataset and use all the other features to predict Fertility. Find the top 3 features using both select k best and recursive feature elimination (use the functions you just built to help you out).

In [39]:
swiss = data("swiss")

In [40]:
swiss

,Fertility,Agriculture,Examination,Education,Catholic,Infant.Mortality
Courtelary,80.2,17.0,15,12,9.96,22.2
Delemont,83.1,45.1,6,9,84.84,22.2
Franches-Mnt,92.5,39.7,5,5,93.40,20.2
Moutier,85.8,36.5,12,7,33.77,20.3
Neuveville,76.9,43.5,17,15,5.16,20.6
Porrentruy,76.1,35.3,9,7,90.57,26.6
Broye,83.8,70.2,16,7,92.85,23.6
Glane,92.4,67.8,14,8,97.16,24.9
Gruyere,82.4,53.3,12,7,97.67,21.0
Sarine,82.9,45.2,16,13,91.38,24.4
Veveyse,87.1,64.5,14,6,98.61,24.5
Aigle,64.1,62.0,21,12,8.52,16.5
Aubonne,66.9,67.5,14,7,2.27,19.1
Avenches,68.9,60.7,19,12,4.43,22.7
Cossonay,61.7,69.3,22,5,2.82,18.7
Echallens,68.3,72.6,18,2,24.20,21.2
Grandson,71.7,34.0,17,8,3.30,20.0
Lausanne,55.7,19.4,26,28,12.11,20.2
La Vallee,54.3,15.2,31,20,2.15,10.8
Lavaux,65.1,73.0,19,9,2.84,20.0
Morges,65.5,59.8,22,10,5.23,18.0
Moudon,65.0,55.1,14,3,4.52,22.4
Nyone,56.6,50.9,22,12,15.14,16.7
Orbe,57.4,54.1,20,6,4.20,15.3
Oron,72.5,71.2,12,1,2.40,21.0
Payerne,74.2,58.1,14,8,5.23,23.8
Paysd'enhaut,72.0,63.5,6,3,2.56,18.0
Rolle,60.5,60.8,16,10,7.72,16.3
Vevey,58.3,26.8,25,19,18.46,20.9
Yverdon,65.4,49.5,15,8,6.10,22.5
Conthey,75.5,85.9,3,2,99.71,15.1
Entremont,69.3,84.9,7,6,99.68,19.8
Herens,77.3,89.7,5,2,100.00,18.3
Martigwy,70.5,78.2,12,6,98.96,19.4
Monthey,79.4,64.9,7,3,98.22,20.2
St Maurice,65.0,75.9,9,9,99.06,17.8
Sierre,92.2,84.6,3,3,99.46,16.3
Sion,79.3,63.1,13,13,96.83,18.1
Boudry,70.4,38.4,26,12,5.62,20.3
La Chauxdfnd,65.7,7.7,29,11,13.79,20.5
Le Locle,72.7,16.7,22,13,11.22,18.9
Neuchatel,64.4,17.6,35,32,16.92,23.0
Val de Ruz,77.6,37.6,15,7,4.97,20.0
ValdeTravers,67.6,18.7,25,7,8.65,19.5
V. De Geneve,35.0,1.2,37,53,42.34,18.0
Rive Droite,44.7,46.6,16,29,50.43,18.2
Rive Gauche,42.8,27.7,22,29,58.33,19.3

In [41]:
swiss.info()

<class 'pandas.core.frame.DataFrame'>
Index: 47 entries, Courtelary to Rive Gauche
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Fertility         47 non-null     float64
 1   Agriculture       47 non-null     float64
 2   Examination       47 non-null     int64
 3   Education         47 non-null     int64
 4   Catholic          47 non-null     float64
 5   Infant.Mortality  47 non-null     float64
dtypes: float64(4), int64(2)
memory usage: 2.6+ KB

In [42]:
#assign everything to X except Fertility because we are using it as our y
X= swiss.drop(columns=['Fertility'])
#assign y_train 
y = swiss['Fertility']

In [43]:
#Use the "select_Kbest" function we created to find our top 3 features
select_kbest(X, y,3)

In [ ]:
#Use the "rfe" function we created to find our top 3 features
rfe(X, y, 3)

In [ ]:
# creating sample of data 
X_sample = swiss.sample(frac=.5)

In [ ]:
#create a function to split our data
def split_data(df):
    '''
    split our data,
    takes in a pandas dataframe
    returns: three pandas dataframes, train, test, and validate
    '''
    #create train_validate and test datasets
    train, test = train_test_split(df, train_size = 0.8, random_state = 123)
    #create train and validate datasets
    train, validate = train_test_split(train, train_size = 0.7, random_state = 123)

    # Have function print datasets shape
    print(f'train -> {train.shape}')
    print(f'validate -> {validate.shape}')
    print(f'test -> {test.shape}')
   
    return train, validate, test

In [ ]:
#assign to variable #need scaler for each independent variable
#create it
scaler = MinMaxScaler()

In [ ]:
cols = ['Agriculture','Examination','Education','Catholic','infant_mortality']

In [ ]:
#fit it
scaler.fit(X_train)
MinMaxScaler()

In [ ]:
X

In [ ]:
#use it
#make a new column within train
#use 'transform' instead of 'predict'
X_train_scaled = scaler.transform(X_train)
X_validate_scaled = scaler.transform(X_validate)
X_test_scaled = scaler.transform(X_test)